services:
  - type: web
    name: butikprojesi-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: CONN
        value: Data Source=/var/data/butik.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
