name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build API
      run: dotnet build ButikProjesi.API --configuration Release --no-restore
    
    - name: Build Client
      run: dotnet build ButikProjesi.Istemci --configuration Release --no-restore
    
    - name: Publish API
      run: dotnet publish ButikProjesi.API --configuration Release --output ./publish/api
    
    - name: Publish Client
      run: dotnet publish ButikProjesi.Istemci --configuration Release --output ./publish/client
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'butiklife-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './publish/api'
    
    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "ButikProjesi.Istemci"
        output_location: "wwwroot"


