name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: [ 'ButikProjesi.Istemci/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore ButikProjesi.Istemci/ButikProjesi.Istemci.csproj
    
    - name: Build and publish
      run: |
        dotnet publish ButikProjesi.Istemci/ButikProjesi.Istemci.csproj -c Release -o ./publish --no-restore
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish/wwwroot
